sudo: required
services:
  - docker

before_install:
  - docker build -t sauryaacharya/fib-client-test -f Dockerfile.dev .

script:
  - docker run -e CI=true sauryaacharya/fib-client-test yarn test --coverage

after_success:
  - docker build -t sauryaacharya/fib-client .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sauryaacharya/fib-client
