sudo: required
services:
  - docker

before_install:
  - docker build -t sauryaacharya/fib-client-test -f Dockerfile.dev .

script:
  - docker run -e CI=true sauryaacharya/fib-client-test yarn test --coverage

after_success:
  - docker build -t sauryaacharya/fib-client .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sauryaacharya/fib-client

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-app"
  env: "DockerApp-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-584309919801"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
